name: html check
on: [push]
jobs:
  check-html-htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chabad360/htmlproofer@master
        with:
          directory: "./"
          # The directory to scan
          arguments: --allow-missing-href --disable-external
  deploy:
     runs-on: ubuntu-latest
     needs: [check-html-htmlproofer]
     if: success() && github.ref == 'refs/heads/main'
     steps:
       - uses: actions/checkout@v2
       - name: Deploy app
         env:
           access_id: ${{secret.ACCESS_ID}}
           key: ${{secret.KEY}}
         run: mkdir -p ~/.aws
         run: echo "[deploymentuser-005240044a15e466]" > ~/.aws/credentials
         run: echo "aws_access_key_id=$access_id" >> ~/.aws/credentials
         run: echo "aws_secret_access_key=$key" >> ~/.aws/credentials
         run: ../scripts/deploy.sh
     



