name: html check
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - id: html-check
        uses: chabad360/htmlproofer@master
        with:
          directory: "./"
                # The directory to scan
          arguments: --allow-missing-href --disable-external
      - id: deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: "./"
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
    
       
     



