name: html check
on: [push]
jobs:
  check-html-htmlproofer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chabad360/htmlproofer@master
        with:
          directory: "./"
          # The directory to scan
          arguments: --allow-missing-href --disable-external



